# Generated by Django 4.2.5 on 2023-10-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("autenticacion", "0004_alter_perfilusuario_fecha_nacimiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "estudiantes",
                    models.ManyToManyField(
                        related_name="cursos_inscritos",
                        to="autenticacion.perfilusuario",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="autenticacion.perfilusuario",
                    ),
                ),
            ],
        ),
    ]
