# Generated by Django 4.2.5 on 2023-10-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dummy_field", models.CharField(max_length=100)),
            ],
            options={
                "db_table": None,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CursoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_alumno", models.CharField(max_length=150)),
                ("nombre_curso", models.CharField(max_length=100)),
            ],
        ),
    ]
