# Generated by Django 4.2.5 on 2023-10-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_cursos_cursousuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CursoUsuario",
        ),
        migrations.DeleteModel(
            name="Cursos",
        ),
    ]
